### ISSUE TITLE
manage.py: lint command fails due to missing release-schema.json

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/european-union-support#100]
To reproduce, run `./manage.py lint output/mapping/eforms/guidance.yaml`. The command fails with the following error:

```
Traceback (most recent call last):
  File "./manage.py", line 877, in <module>
    cli()
  File "/home/ddewhurst/.pyenv/versions/european-union-support/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ddewhurst/.pyenv/versions/european-union-support/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ddewhurst/.pyenv/versions/european-union-support/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ddewhurst/.pyenv/versions/european-union-support/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ddewhurst/.pyenv/versions/european-union-support/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "./manage.py", line 472, in lint
    with open('release-schema.json') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'release-schema.json'
```

**Comment by jpmckinney** [comment]
I've added an instruction to get the file.
