### ISSUE TITLE
manage.py: lint command fails due to anchor not found error

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/european-union-support#101]
To resolve the error reported in #100, I downloaded a copy of the patched release schema from the EU profile and ran `./manage.py lint output/mapping/eforms/guidance.yaml`. The command fails with the following error:

```
Traceback (most recent call last):
  File "./manage.py", line 877, in <module>
    cli()
  File "/home/ddewhurst/.pyenv/versions/european-union-support/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ddewhurst/.pyenv/versions/european-union-support/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ddewhurst/.pyenv/versions/european-union-support/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ddewhurst/.pyenv/versions/european-union-support/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ddewhurst/.pyenv/versions/european-union-support/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "./manage.py", line 498, in lint
    assert sdk_documents[base_url].xpath(f'//@id="{fragment}"'), f'{identifier}: anchor not found: {fragment}'
AssertionError: BT-132(t)-Lot: anchor not found: openingEventSection'
```

**Comment by jpmckinney** [comment]
Right, so you had a trailing `'` character, which I removed in a22d7077f6ceeac2b911262ef89bc4f6a85bc1c7
